#!/bin/bash

# 🎯 GUIA PRÁTICO: Testando a Sincronização de Dados

echo "╔════════════════════════════════════════════════════════════╗"
echo "║  TESTE PRÁTICO: SINCRONIZAÇÃO DE DADOS ENTRE DISPOSITIVOS  ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

# Cores para melhor visualização
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}📋 PASSO 1: Preparar o Ambiente${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1.1) Abra DOIS terminais diferentes:"
echo ""
echo -e "  Terminal 1 (Backend):"
echo "  $ cd /Users/henriquecesararaujoferreira/Desktop/Cadastro/server"
echo "  $ npm run dev"
echo ""
echo -e "  Terminal 2 (Frontend):"
echo "  $ cd /Users/henriquecesararaujoferreira/Desktop/Cadastro"
echo "  $ npm run dev"
echo ""
echo "1.2) Aguarde até aparecer:"
echo "  ✓ 'Servidor AAFAB rodando na porta 3001'"
echo "  ✓ 'VITE v... ready in ... ms'"
echo ""

echo -e "${BLUE}📋 PASSO 2: Teste no COMPUTADOR${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "2.1) Abra o navegador: http://localhost:3000"
echo ""
echo "2.2) Faça o cadastro:"
echo "  • CPF: Qualquer CPF válido (ex: 12345678901)"
echo "  • Nome: Seu nome completo"
echo "  • Email: seu@email.com"
echo "  • Preencha os outros campos"
echo "  • Marque o termo de consentimento"
echo "  • Clique em ENVIAR"
echo ""
echo "2.3) Veja a mensagem:"
echo "  ✅ 'Cadastro enviado com sucesso!'"
echo ""
echo "2.4) Clique em ABRIR PAINEL e veja:"
echo "  ✅ Seus dados aparecem no painel admin"
echo ""

echo -e "${BLUE}📋 PASSO 3: Teste no CELULAR${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "3.1) Descubra o IP do seu Mac:"
echo "  $ ifconfig | grep 'inet ' | grep -v 127"
echo ""
echo "  Vai aparecer algo como: inet 192.168.1.100"
echo ""
echo "3.2) No celular, acesse:"
echo "  http://192.168.1.100:3000"
echo ""
echo "3.3) Clique no botão 'Admin' no topo"
echo ""
echo "3.4) Digite a senha:"
echo "  ${GREEN}AAFAB@2026#Secure!${NC}"
echo ""
echo "3.5) Clique em 'Painel Admin'"
echo ""
echo "3.6) 🎉 RESULTADO ESPERADO:"
echo "  ${GREEN}✅ VER SEU CADASTRO QUE FOI FEITO NO COMPUTADOR${NC}"
echo ""
echo "  Mesmo que nunca tenha se cadastrado no celular!"
echo ""

echo -e "${BLUE}📋 PASSO 4: Verificar Sincronização${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "4.1) No computador, abra o console (F12)"
echo ""
echo "4.2) Procure por mensagens como:"
echo "  ✓ 'Erro ao conectar ao backend: ...' (normal em mobile)"
echo "  ✓ 'Listagem de cadastros acessada'"
echo ""
echo "4.3) Acesse o Neon Console para confirmar:"
echo "  https://console.neon.tech"
echo ""
echo "  Veja a tabela 'Cadastro' com seus dados"
echo ""

echo -e "${BLUE}📋 PASSO 5: Teste de Erro (Esperado)${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "5.1) Se fechar o terminal do Backend:"
echo "  • Computador: Mostra erro de conexão ✓ (esperado)"
echo "  • Celular: Continua mostrando dados do localStorage ✓"
echo ""
echo "5.2) Isso prova que o offline-first funciona!"
echo ""

echo -e "${GREEN}════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}✅ SOLUÇÃO PRONTA PARA USAR!${NC}"
echo -e "${GREEN}════════════════════════════════════════════════════════${NC}"
echo ""
echo "🎯 O que foi corrigido:"
echo "  ✅ Dados salvos no Neon (banco de dados na nuvem)"
echo "  ✅ Sincronizados entre dispositivos"
echo "  ✅ Acessível de celular e computador"
echo "  ✅ Funciona offline com cache local"
echo "  ✅ Segurança com autenticação JWT"
echo ""
echo "📞 Se tiver problemas:"
echo "  1) Verifique se backend está rodando (porta 3001)"
echo "  2) Verifique se frontend está rodando (porta 3000)"
echo "  3) Limpe o cache do navegador (Ctrl+Shift+Del)"
echo "  4) Recarregue a página (F5)"
echo ""
